cta:
  bucket: null
  version: null
  domain: null
name: erikphotographic
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.17505
color:
  saturation: 0.9486341078300029
  brandStrength: 0.375
  rhythmicContrast: 0.3569331599865109
  brandColors:
    - '#181e24'
    - '#404447'
    - '#beb9ad'
    - '#838077'
    - '#ded8ce'
  lightness: 0.562521900748834
layout_spectrum: 0
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
