name: erikphotographic
favicon: null
layout_spectrum: 0.40416606049984694
typography_spectrum: 0.24142313026823103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.38487184420228004
  lightness: 0.562521900748834
  saturation: 0.9486341078300029
  rhythmicContrast: 0.3569331599865109
purpose: []
