name: erikphotographic
favicon: null
layout_spectrum: 0.58701
typography_spectrum: 0.24142313026823103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181e24'
    - '#404447'
    - '#beb9ad'
    - '#838077'
    - '#ded8ce'
  brandStrength: 0.375
  lightness: 0.562521900748834
  saturation: 0.9486341078300029
  rhythmicContrast: 0.3569331599865109
purpose: []
